import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import DataContext from "./context/DataContext";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Crypto price Tracker",
  description: "Generated by create next app", // to be edited later
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <DataContext>
        <AppRouterCacheProvider>
          <body
            className={` ${geistSans.variable} ${geistMono.variable} antialiased ${roboto.variable} bg-white `}
          >
            <ThemeProvider theme={theme}>
              {children}
            </ThemeProvider>
          </body>

        </AppRouterCacheProvider>
      </DataContext>
    </html>
  );
}
